/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public final class MainUtama extends javax.swing.JFrame {
    public int keterlambatan,hasil;
    //
    private static Connection conn;
    private static Statement stat;
    private static ResultSet rs;
    private static DefaultTableModel model;
    private static DefaultTableModel model2;
    //
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;

    public MainUtama(String input) {
        initComponents();
        conn = Koneksi.koneksi();
        
        //parameter
        email_user.setText(input);
        //menampilkan profile
        param();
        //warna
        warna();
        lbl_no.setBackground(new Color(0,0,0,0));
        tf_minus_stok.setBackground(new Color(0,0,0,0));
//        
        //tabelbuku
        
    getDatabuku();
        //tabelrekap
    getDataRekap();
    //    
    notEditabel();
    //
    tanggalHariIni();
    waktu();
    }

    MainUtama() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JPanel();
        kiripane = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        btnLibrary = new javax.swing.JLabel();
        btnArticle = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        gambarkiri = new javax.swing.JLabel();
        kananpane = new javax.swing.JPanel();
        gambarwelcome = new javax.swing.JLabel();
        RekapPane = new javax.swing.JPanel();
        btn_cetak = new javax.swing.JButton();
        brn_pulih = new javax.swing.JButton();
        btn_cetak1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelRekap = new javax.swing.JTable();
        buku_pinjam = new javax.swing.JLabel();
        tf_pinjam = new javax.swing.JLabel();
        nama_pinjam = new javax.swing.JLabel();
        tgl_pinjamac = new javax.swing.JLabel();
        tgl_kembali = new javax.swing.JLabel();
        lbl_kelas_kmbl = new javax.swing.JLabel();
        tf_denda = new javax.swing.JLabel();
        tf_telat = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tf_tglHariIni = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_no = new javax.swing.JTextField();
        gambarrekap = new javax.swing.JLabel();
        profilepane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        email_user = new javax.swing.JTextField();
        nama_user = new javax.swing.JTextField();
        pass_user = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        kelas_user = new javax.swing.JTextField();
        hp_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        gambar_User = new javax.swing.JLabel();
        path = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        gambarprofile = new javax.swing.JLabel();
        Librarypane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tf_cari = new javax.swing.JTextField();
        lbl_kelaspinjam = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        tf_buku = new javax.swing.JTextField();
        tf_jmlhBuku = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        tglkmbl = new com.toedter.calendar.JDateChooser();
        btn_preview = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_pinjam = new javax.swing.JButton();
        lbl_nobuku = new javax.swing.JLabel();
        lbl_kelaspinjam1 = new javax.swing.JLabel();
        lbl_kelaspinjam2 = new javax.swing.JLabel();
        lbl_kelaspinjam3 = new javax.swing.JLabel();
        lbl_kelaspinjam4 = new javax.swing.JLabel();
        lbl_kelaspinjam5 = new javax.swing.JLabel();
        lbl_kelaspinjam6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_minus_stok = new javax.swing.JTextField();
        gambarLibrary = new javax.swing.JLabel();
        AboutPane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libeeo User");
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPane.setBackground(new java.awt.Color(255, 255, 255));
        MainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kiripane.setBackground(new java.awt.Color(0, 0, 0));
        kiripane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfile.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(1, 193, 198));
        btnProfile.setText("I");
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfileMouseExited(evt);
            }
        });
        kiripane.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 243, 223, 40));

        btnLibrary.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLibrary.setForeground(new java.awt.Color(1, 193, 198));
        btnLibrary.setText("I");
        btnLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibraryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibraryMouseExited(evt);
            }
        });
        kiripane.add(btnLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 308, 223, 40));

        btnArticle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnArticle.setForeground(new java.awt.Color(1, 193, 198));
        btnArticle.setText("I");
        btnArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArticleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArticleMouseExited(evt);
            }
        });
        kiripane.add(btnArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 370, 223, 40));

        btnAbout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(1, 193, 198));
        btnAbout.setText("I");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        kiripane.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 436, 223, 40));

        btnLogout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(1, 193, 198));
        btnLogout.setText("I");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        kiripane.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 525, 223, 40));

        gambarkiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kiri user.jpg"))); // NOI18N
        kiripane.add(gambarkiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        MainPane.add(kiripane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 600));

        kananpane.setBackground(new java.awt.Color(255, 255, 255));
        kananpane.setLayout(new java.awt.CardLayout());

        gambarwelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kanan user.jpg"))); // NOI18N
        gambarwelcome.setText("jLabel2");
        kananpane.add(gambarwelcome, "card2");

        RekapPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cetak.setBackground(new java.awt.Color(255, 255, 255));
        btn_cetak.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-print-20.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        RekapPane.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 100, 30));

        brn_pulih.setBackground(new java.awt.Color(255, 255, 255));
        brn_pulih.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        brn_pulih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-back-arrow-20.png"))); // NOI18N
        brn_pulih.setText("Kembalikan");
        brn_pulih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_pulihActionPerformed(evt);
            }
        });
        RekapPane.add(brn_pulih, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 123, 120, 30));

        btn_cetak1.setBackground(new java.awt.Color(255, 255, 255));
        btn_cetak1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_cetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-refresh-20.png"))); // NOI18N
        btn_cetak1.setText("Refresh");
        btn_cetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak1ActionPerformed(evt);
            }
        });
        RekapPane.add(btn_cetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 123, 100, 30));

        tabelRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID User", "Buku", "Dipinjam"
            }
        ));
        tabelRekap.setFocusable(false);
        tabelRekap.setGridColor(new java.awt.Color(255, 255, 255));
        tabelRekap.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelRekap.setRowHeight(25);
        tabelRekap.setSelectionBackground(new java.awt.Color(31, 200, 199));
        tabelRekap.setShowVerticalLines(false);
        tabelRekap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRekapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelRekap);
        if (tabelRekap.getColumnModel().getColumnCount() > 0) {
            tabelRekap.getColumnModel().getColumn(0).setResizable(false);
            tabelRekap.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        RekapPane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 740, 420));

        buku_pinjam.setText("buku_pinjam");
        RekapPane.add(buku_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        tf_pinjam.setText("tf_pinjam");
        RekapPane.add(tf_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        nama_pinjam.setText("nama_pinjam");
        RekapPane.add(nama_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        tgl_pinjamac.setText("tgl_pinjam");
        RekapPane.add(tgl_pinjamac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        tgl_kembali.setText("tgl_kembali");
        RekapPane.add(tgl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        lbl_kelas_kmbl.setText("lbl_kelas_kmbl");
        RekapPane.add(lbl_kelas_kmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        tf_denda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_denda.setForeground(new java.awt.Color(255, 255, 255));
        tf_denda.setText("_");
        RekapPane.add(tf_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 20));

        tf_telat.setText("telat hari");
        RekapPane.add(tf_telat, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-coins-20.png"))); // NOI18N
        jButton2.setText("Denda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        RekapPane.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 123, 100, 30));

        tf_tglHariIni.setText("tgl hari ini");
        RekapPane.add(tf_tglHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Denda");
        RekapPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rp,");
        RekapPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 50, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pengembalian Buku_______");
        RekapPane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lbl_no.setBorder(null);
        RekapPane.add(lbl_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 40, -1));

        gambarrekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/blank.jpg"))); // NOI18N
        RekapPane.add(gambarrekap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(RekapPane, "card5");

        profilepane.setBackground(new java.awt.Color(255, 255, 255));
        profilepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-20.png"))); // NOI18N
        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        profilepane.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 543, 310, 30));
        profilepane.add(email_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 310, 30));
        profilepane.add(nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 310, 30));
        profilepane.add(pass_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 310, 30));

        lbl_id.setText("idUser");
        profilepane.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));
        profilepane.add(kelas_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 310, 30));
        profilepane.add(hp_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        profilepane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 505, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        profilepane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 345, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kelas");
        profilepane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 385, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        profilepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 425, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No HP");
        profilepane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 465, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/camera3.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });
        profilepane.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 50, 50));

        gambar_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon gambar.jpg"))); // NOI18N
        profilepane.add(gambar_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 150, 150));

        path.setText("jLabel8");
        profilepane.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 130, 520, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Profile_______");
        profilepane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("*ukuran gambar max 1MB");
        profilepane.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, -1));

        gambarprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/blank.jpg"))); // NOI18N
        profilepane.add(gambarprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        kananpane.add(profilepane, "card3");

        Librarypane.setBackground(new java.awt.Color(255, 255, 255));
        Librarypane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Buku", "Nama", "Stok"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(31, 200, 199));
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Librarypane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 340, 310));

        tf_cari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_cari.setForeground(new java.awt.Color(255, 255, 255));
        tf_cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_cari.setText("Cari Buku...");
        tf_cari.setToolTipText("");
        tf_cari.setBorder(null);
        tf_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cariMouseClicked(evt);
            }
        });
        tf_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_cariKeyReleased(evt);
            }
        });
        Librarypane.add(tf_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 340, 30));

        lbl_kelaspinjam.setEditable(false);
        lbl_kelaspinjam.setBackground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_kelaspinjam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lbl_kelaspinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lbl_kelaspinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_kelaspinjamActionPerformed(evt);
            }
        });
        Librarypane.add(lbl_kelaspinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 100, 30));

        tf_nama.setEditable(false);
        tf_nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Librarypane.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 270, 30));

        tf_buku.setEditable(false);
        tf_buku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_buku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_buku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Librarypane.add(tf_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 270, 30));

        tf_jmlhBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_jmlhBuku.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_jmlhBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tf_jmlhBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_jmlhBukuKeyTyped(evt);
            }
        });
        Librarypane.add(tf_jmlhBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 30));

        tglpinjam.setBackground(new java.awt.Color(255, 255, 255));
        tglpinjam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tglpinjam.setForeground(new java.awt.Color(255, 255, 255));
        tglpinjam.setDateFormatString("yyyy-MM-dd");
        tglpinjam.setDoubleBuffered(false);
        tglpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tglpinjamMouseEntered(evt);
            }
        });
        Librarypane.add(tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 270, 40));

        tglkmbl.setBackground(new java.awt.Color(255, 255, 255));
        tglkmbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tglkmbl.setForeground(new java.awt.Color(255, 255, 255));
        tglkmbl.setDateFormatString("yyyy-MM-dd");
        tglkmbl.setDoubleBuffered(false);
        tglkmbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tglkmblMouseEntered(evt);
            }
        });
        Librarypane.add(tglkmbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 270, 40));

        btn_preview.setBackground(new java.awt.Color(255, 255, 255));
        btn_preview.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-view-20.png"))); // NOI18N
        btn_preview.setText("Preview");
        btn_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previewActionPerformed(evt);
            }
        });
        Librarypane.add(btn_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 120, 40));

        btn_refresh.setBackground(new java.awt.Color(255, 255, 255));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-refresh-20.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        Librarypane.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 100, 40));

        btn_pinjam.setBackground(new java.awt.Color(255, 255, 255));
        btn_pinjam.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-20.png"))); // NOI18N
        btn_pinjam.setText("Pinjam");
        btn_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pinjamActionPerformed(evt);
            }
        });
        Librarypane.add(btn_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 100, 40));

        lbl_nobuku.setForeground(new java.awt.Color(255, 255, 255));
        Librarypane.add(lbl_nobuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        lbl_kelaspinjam1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kelaspinjam1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam1.setText("Tgl Kembali");
        Librarypane.add(lbl_kelaspinjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        lbl_kelaspinjam2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kelaspinjam2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam2.setText("Nama");
        Librarypane.add(lbl_kelaspinjam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lbl_kelaspinjam3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kelaspinjam3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam3.setText("Kelas");
        Librarypane.add(lbl_kelaspinjam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lbl_kelaspinjam4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kelaspinjam4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam4.setText("Buku");
        Librarypane.add(lbl_kelaspinjam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lbl_kelaspinjam5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kelaspinjam5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam5.setText("Jumlah");
        Librarypane.add(lbl_kelaspinjam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, -1));

        lbl_kelaspinjam6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kelaspinjam6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kelaspinjam6.setText("Tgl Pinjam");
        Librarypane.add(lbl_kelaspinjam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pinjam Buku_______");
        Librarypane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tf_minus_stok.setBorder(null);
        Librarypane.add(tf_minus_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 50, -1));

        gambarLibrary.setBackground(new java.awt.Color(255, 255, 255));
        gambarLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/blank.jpg"))); // NOI18N
        gambarLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gambarLibraryMouseEntered(evt);
            }
        });
        Librarypane.add(gambarLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(Librarypane, "card3");

        AboutPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tentang App_______");
        AboutPane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Versi 1.0");
        AboutPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Libeeo App yang dibuat oleh kami, siswa dan siswi SMKN 1 Gending kelas  12 RPL 1");
        AboutPane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tim kami bernama Dream Team, dimana anggotanya adalah :");
        AboutPane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 275, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("- Samsul Hadi");
        AboutPane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("- Lailiatus Sa'diyah");
        AboutPane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 305, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("- Nur Fadiilah Wardatul Jannah");
        AboutPane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("- Prisma Tri Hadi");
        AboutPane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 335, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Diharapkan aplikasi ini dapat membantu siswa/siswi dalam transaksi pinjam meminjam");
        AboutPane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("buku di Sekolah ");
        AboutPane.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 365, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("buku di sekolah. ");
        AboutPane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 245, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Libeeo merupakan aplikasi yang dapat digunakan untuk transaksi pinjam meminjam");
        AboutPane.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/blank.jpg"))); // NOI18N
        AboutPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 600));

        kananpane.add(AboutPane, "card6");

        MainPane.add(kananpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 0, 764, 600));

        getContentPane().add(MainPane, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(profilepane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnLibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(Librarypane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnLibraryMouseClicked

    private void btnArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(RekapPane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnArticleMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(AboutPane);
        kananpane.repaint();
        kananpane.revalidate();
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Keluar ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:    
                new main_awal().setVisible(true);
                this.dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseEntered
        // TODO add your handling code here:
        btnProfile.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnProfileMouseEntered

    private void btnProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseExited
        // TODO add your handling code here:
        btnProfile.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnProfileMouseExited

    private void btnLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseEntered
        // TODO add your handling code here:
        btnLibrary.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnLibraryMouseEntered

    private void btnLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibraryMouseExited
        // TODO add your handling code here:
        btnLibrary.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnLibraryMouseExited

    private void btnArticleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseEntered
        // TODO add your handling code here:
        btnArticle.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnArticleMouseEntered

    private void btnArticleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticleMouseExited
        // TODO add your handling code here:
       btnArticle.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnArticleMouseExited

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        btnAbout.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        btnAbout.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnAboutMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(new Color(1,193,198));

    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.WHITE);

    }//GEN-LAST:event_btnLogoutMouseExited

    private void tf_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cariMouseClicked
        // TODO add your handling code here:
        tf_cari.setText("");
    }//GEN-LAST:event_tf_cariMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        
          bersih();
          model.setRowCount(0);
          getDatabuku();
         
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pinjamActionPerformed
        // TODO add your handling code here:
        String nama = tf_nama.getText();
        String buku = tf_buku.getText();
        String jmlhbuku = tf_jmlhBuku.getText();
    
        int minus = Integer.parseInt(tf_minus_stok.getText());
        int stok = Integer.parseInt(tf_jmlhBuku.getText());
        
        if (tf_nama.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom kosong");
                }else if(tf_buku.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "tidak ada buku yang dipilih!!");            
                }else if(minus < stok){
                    JOptionPane.showMessageDialog(this, "Stok tidak mencukupi!!!");
                }
            else{
                try {
                    //tanggal
                String frmt = "yyyy-MM-dd";
                SimpleDateFormat sdf = new SimpleDateFormat(frmt);
                String pinjam = String.valueOf(sdf.format(tglpinjam.getDate()));
                String kembali = String.valueOf(sdf.format(tglkmbl.getDate()));
                    String sql = "insert into pinjam (nama,kelas,buku,jmlhbuku,tglPinjam,tglKmbl) values (?,?,?,?,?,?)";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, nama);
                    ps.setString(2, lbl_kelaspinjam.getText());
                    ps.setString(3, buku);
                    ps.setString(4, jmlhbuku);
                    ps.setString(5, pinjam);
                    ps.setString(6, kembali);
                ps.executeUpdate();
                try {
                    String sql2 = "insert into history (nama,kelas,buku,jmlhbuku,tglPinjam,tglKmbl) values (?,?,?,?,?,?)";
                        PreparedStatement ps2 = conn.prepareStatement(sql2);
                        ps2.setString(1, nama);
                        ps2.setString(2, lbl_kelaspinjam.getText());
                        ps2.setString(3, buku);
                        ps2.setString(4, jmlhbuku);
                        ps2.setString(5, pinjam);
                        ps2.setString(6, kembali);
                    ps2.executeUpdate();
            } catch (SQLException e) {
            }
        model.setRowCount(0);
        getDatabuku();
        model2.setRowCount(0);
        getDataRekap();
        bersih();
        JOptionPane.showMessageDialog(this, "Berhasil Meminjam Buku >.<");
        pindah();
        } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan "+e);
        }
                }
        
    }//GEN-LAST:event_btn_pinjamActionPerformed

    private void tglkmblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglkmblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkmblMouseEntered

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String nobuku = jTable1.getValueAt(baris, 0).toString();
        String nama = jTable1.getValueAt(baris, 1).toString();
        String minus = jTable1.getValueAt(baris, 3).toString();
        tf_buku.setText(nama);
        lbl_nobuku.setText(nobuku);
        tf_minus_stok.setText(minus);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previewActionPerformed
        // Preview Gambar
        if (lbl_nobuku.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "tidak ada buku yang dipilih!!");
        }else{
            String nobuku = lbl_nobuku.getText();
            new ReviewBuku(nobuku).setVisible(true);
        }
    }//GEN-LAST:event_btn_previewActionPerformed

    private void tf_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cariKeyReleased
        // TODO add your handling code here:
        int jumlahrow = jTable1.getRowCount();
        for(int n=0; n<jumlahrow; n++){
            model.removeRow(0);
        }
        try {
        String sql ="select*from buku where nama like '%"+tf_cari.getText()+"%'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        int no = 1;
        while (rs.next()) {
            Object[] o = new Object[4];
            o[0] = rs.getString("no");
            o[1] = rs.getString("nama");
            o[2] = rs.getString("penulis");
            o[3] = rs.getString("stok");
            model.addRow(o);
            no++;
        }
        jTable1.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Cari eroor "+e);
    }
    }//GEN-LAST:event_tf_cariKeyReleased

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try {
            String report = ("C:\\Program Files (x86)\\Dreams Team\\Libeeo\\src\\reportEdu\\user.jrxml");
            HashMap hash = new HashMap();
            hash.put("nama_user", nama_user.getText());
            JasperReport jrpt = JasperCompileManager.compileReport(report);
            JasperPrint jprint = JasperFillManager.fillReport(jrpt, hash, conn);
            JasperViewer.viewReport(jprint, false);
        } catch (JRException Ejrpt) {
            System.out.println("report gagal karena "+Ejrpt);
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void brn_pulihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_pulihActionPerformed
    // TODO add your handling code here: 
    
        String nama = nama_pinjam.getText();
        String buku = buku_pinjam.getText();
        String jmlhbuku = tf_pinjam.getText();
        String pinjam = tgl_kembali.getText();
        String kembali = tf_tglHariIni.getText();
        String denda = tf_denda.getText();
        //
        if (tf_nama.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom tidak boleh kosong");
                }else if (buku_pinjam.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom tidak boleh kosong");            
            }
            else{
            try {
                String sql="insert into kembali(nama, kelas, buku, jmlhBuku, tglPinjam, tglKmbl, denda) values(?,?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, nama);
                ps.setString(2, lbl_kelas_kmbl.getText());
                ps.setString(3, buku);
                ps.setString(4, jmlhbuku);
                ps.setString(5, pinjam);
                ps.setString(6, kembali);
                ps.setString(7, denda);
                ps.executeUpdate();
                try {
                    String sql2="delete from pinjam where no ='"+lbl_no.getText()+"'";
                    PreparedStatement ps2 = conn.prepareStatement(sql2);
                    ps2.executeUpdate();
                    //                    
                    model2.setRowCount(0);
                    getDataRekap();
                    model.setRowCount(0);
                    getDatabuku();
                     bersihrekap();
                    //
                } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "gagal menghapus"+ex.getMessage());            
        }
        JOptionPane.showMessageDialog(this, "Berhasil mengembalikan Buku");
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Mencetak Transaksi Ini?");
        switch(opsi){
            case JOptionPane.YES_OPTION:    
                cetakkmbl();
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
            bersihrekap();
        } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "gagal mengembalikan buku"+e.getMessage());            
        }
                }
        
        
    }//GEN-LAST:event_brn_pulihActionPerformed

    private void tabelRekapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRekapMouseClicked
        // TODO add your handling code here:
        
        //
        int baris = tabelRekap.rowAtPoint(evt.getPoint());
        //
        String notabel = tabelRekap.getValueAt(baris, 0).toString();
        String nama = tabelRekap.getValueAt(baris, 1).toString();
        String buku = tabelRekap.getValueAt(baris, 2).toString();
        String dipinjam = tabelRekap.getValueAt(baris, 3).toString();
        String tglPinjamm = tabelRekap.getValueAt(baris, 4).toString();
        String tglKmbll = tabelRekap.getValueAt(baris, 5).toString();


        buku_pinjam.setText(buku);
        tf_pinjam.setText(dipinjam);
        nama_pinjam.setText(nama);
        tgl_pinjamac.setText(tglPinjamm);
        tgl_kembali.setText(tglKmbll);
        lbl_no.setText(notabel);
        
        denda();
    }//GEN-LAST:event_tabelRekapMouseClicked

    private void gambarLibraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarLibraryMouseEntered
       
        
    }//GEN-LAST:event_gambarLibraryMouseEntered

    private void btn_cetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak1ActionPerformed
        // TODO add your handling code here:
          model2.setRowCount(0);
          getDataRekap();
          bersihrekap();
    }//GEN-LAST:event_btn_cetak1ActionPerformed

    private void tf_jmlhBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jmlhBukuKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        else if(tf_jmlhBuku.getText().length()>= 3) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Buku yang dipinjam terlalu banyak!!");
        }
    }//GEN-LAST:event_tf_jmlhBukuKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email2 = email_user.getText();
        String[] check = email2.split("@", 2);
        if (email_user.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom kosong");
                }else if(nama_user.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");            
                }else if (pass_user.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");            
                }else if (pass_user.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom kosong");  
                    //
                }else if(email_user.getText().length()<=10){
                    JOptionPane.showMessageDialog(this, "Karakter email terlalu pendek");
                }else if(pass_user.getText().length()>=13){
                    JOptionPane.showMessageDialog(this, "no Hp terlalu panjang");
                }else if(pass_user.getText().length()<6){
                    JOptionPane.showMessageDialog(this, "password terlalu pendek");   
                }else if(nama_user.getText().length()< 4){
                    JOptionPane.showMessageDialog(this, "nama terlalu pendek");   
                }else if (!"gmail.com".equals(String.valueOf(check[1]))) {
            JOptionPane.showMessageDialog(this, "Isi Email dengan benar!!");
                }
            else{
                try {
            String sql = "update registrasi set "
                    +"email=?, nama=?, password=?, noHP=?, kelas=?, gambar=? "
                    +"where id=?";
            PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, email_user.getText());
                ps.setString(2, nama_user.getText());
                ps.setString(3, pass_user.getText());
                ps.setString(4, hp_user.getText()); 
                ps.setString(5, kelas_user.getText()); 
                ps.setBytes(6, person_image);
                ps.setString(7, lbl_id.getText());
                ps.executeUpdate();
                bersih();
                JOptionPane.showMessageDialog(this, "Data User Berhasil di Update");
                new Login().setVisible(true);
                this.dispose();
        } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "gagal diUPDATE"+e);

        }
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(gambar_User.getWidth(), gambar_User.getHeight(), Image.SCALE_SMOOTH));
        gambar_User.setIcon(imageicon);
        path.setText(filename);
        
        try {
            File image =  new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new  ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            
            for(int readNum; (readNum = fis.read(buff)) !=-1;){
                bos.write(buff,0,readNum);
            }
            person_image = bos.toByteArray();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "input gambar "+e);
        }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon("C:\\Program Files (x86)\\Dreams Team\\Libeeo\\src\\Gambar\\camera2.png");
        jLabel32.setIcon(img);
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon("C:\\Program Files (x86)\\Dreams Team\\Libeeo\\src\\Gambar\\camera3.png");
        jLabel32.setIcon(img);
    }//GEN-LAST:event_jLabel32MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (lbl_no.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "belum ada data yang dipilih!!");
        }else{
        denda();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tglpinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglpinjamMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamMouseEntered

    private void lbl_kelaspinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_kelaspinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_kelaspinjamActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered
    public void param(){
//        gambar_User
        String emailUser = email_user.getText();
        try {
            String sql = "Select*from registrasi where email='"+emailUser+"'";
            stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            //
            while (rs.next()) {
                lbl_id.setText(rs.getString(1));
                nama_user.setText(rs.getString(3));
                pass_user.setText(rs.getString(4));
                hp_user.setText(rs.getString(5));
                kelas_user.setText(rs.getString(6));
//                
                tf_nama.setText(rs.getString(3));
                lbl_kelaspinjam.setText(rs.getString(1));
                lbl_kelaspinjam.setText(rs.getString(6));
                lbl_kelas_kmbl.setText(rs.getString(6));
            }
        } catch (HeadlessException | SQLException e) {
        }
        try {
                    String iduser = lbl_id.getText();
                    String query ="select*from registrasi where email='"+emailUser+"'";
                    stat = conn.createStatement();
                    rs = stat.executeQuery(query);
                        if (rs.next()) {
                       byte[] imagedata = rs.getBytes("gambar");
                       format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(gambar_User.getWidth(), gambar_User.getHeight(), Image.SCALE_SMOOTH));
                       gambar_User.setIcon(format);
                       }
        } catch (SQLException e) {
                   JOptionPane.showMessageDialog(this, "Gambar tidak ada!!"+e.getMessage());                   
        }
}
    public void warna(){
        //
            jTable1.setOpaque(false);
            ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        //
        btnAbout.setForeground(new Color(0,0,0,0));
        btnProfile.setForeground(new Color(0,0,0,0));
        btnLibrary.setForeground(new Color(0,0,0,0));
        btnLogout.setForeground(new Color(0,0,0,0));
        btnArticle.setForeground(new Color(0,0,0,0));
        //
        tglpinjam.setBackground(new Color(0,0,0,0));
        tglkmbl.setBackground(new Color(0,0,0,0));
//        tf_buku.setBackground(new Color(0,0,0,0));
        tf_cari.setBackground(new Color(0,0,0,0));
//        lbl_kelaspinjam.setBackground(new Color(0,0,0,0));
//        tf_nama.setBackground(new Color(0,0,0,0));
//        tf_jmlhBuku.setBackground(new Color(0,0,0,0));
        lbl_nobuku.setForeground(new Color(0,0,0,0));
        lbl_no.setForeground(new Color(0,0,0,0));
//        lbl_no_buku.setForeground(new Color(0,0,0,0));
        lbl_no.setForeground(new Color(0,0,0,0));
        tf_pinjam.setForeground(new Color(0,0,0,0));
        tgl_pinjamac.setForeground(new Color(0,0,0,0));
        nama_pinjam.setForeground(new Color(0,0,0,0));
        tf_tglHariIni.setForeground(new Color(0,0,0,0));
        tgl_kembali.setForeground(new Color(0,0,0,0));
        buku_pinjam.setForeground(new Color(0,0,0,0));
        lbl_kelas_kmbl.setForeground(new Color(0,0,0,0));
        tf_telat.setForeground(new Color(0,0,0,0));
        lbl_id.setForeground(new Color(0,0,0,0));
        path.setForeground(new Color(0,0,0,0));
        tf_minus_stok.setForeground(new Color(0,0,0,0));

        //
//        id_userpinjam.setBackground(new Color(0,0,0,0));
        nama_pinjam.setBackground(new Color(0,0,0,0));
        buku_pinjam.setBackground(new Color(0,0,0,0));
        tf_pinjam.setBackground(new Color(0,0,0,0));
        tgl_kembali.setBackground(new Color(0,0,0,0));
        tgl_pinjamac.setBackground(new Color(0,0,0,0));
      
        //
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(255,255,255));
        jTable1.getTableHeader().setForeground(Color.BLACK);
        //
    
}
    public void bersih(){
        tf_buku.setText("");
        tf_jmlhBuku.setText("");
        lbl_nobuku.setText("");
    }
    public void bersihrekap(){
        nama_pinjam.setText("");
        buku_pinjam.setText("");
        tf_pinjam.setText("");
        tgl_pinjamac.setText("");
        tgl_kembali.setText("");
        tf_denda.setText("_");
        lbl_no.setText("");
    }
    public void getDatabuku(){
        model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("Pengarang");
        model.addColumn("Stok");
    jTable1.setModel(model);
        try {
        String sql ="select*from buku";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] obj = new Object[4];
            obj [0] = rs.getString("no");
            obj [1] = rs.getString("nama");
            obj [2] = rs.getString("penulis");
            obj [3] = rs.getString("stok");
            model.addRow(obj);
        }
        } catch (SQLException e) {
        }
    }
    public void notEditabel(){
    JTextField f = new JTextField();
        f.setEditable(false);
        for (int i = 0; i < tabelRekap.getColumnModel().getColumnCount(); i++) {
        tabelRekap.getColumnModel().getColumn(i).setCellEditor(new DefaultCellEditor(f));
        }
        for (int i = 0; i < jTable1.getColumnModel().getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellEditor(new DefaultCellEditor(f));
        }
    }
    public void getDataRekap(){
        model2 = new DefaultTableModel();
        model2.addColumn("No");
        model2.addColumn("Nama");
        model2.addColumn("Buku");
        model2.addColumn("Dpinjam");
        model2.addColumn("Tanggal Pinjam");
        model2.addColumn("Tanggal Kembali");

    tabelRekap.setModel(model2);
        try {
        String sql ="select*from pinjam where nama='"+nama_user.getText()+"'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            Object[] objk = new Object[6];
            objk [0] = rs.getString("no");
            objk [1] = rs.getString("nama");
            objk [2] = rs.getString("buku");
            objk [3] = rs.getString("jmlhBuku");
            objk [4] = rs.getString("tglPinjam");
            objk [5] = rs.getString("tglKmbl");
            model2.addRow(objk);
        }
        } catch (SQLException e) {
            System.out.println("tabel rekap ada yg salah = "+e);
        }
    }
    public void tanggalHariIni(){
    Date ys = new Date();
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    tf_tglHariIni.setText(s.format(ys));
}
public void denda(){
    DateFormat df = new SimpleDateFormat("yyyy-mm-dd");
try{
//Konversi dari string ke tanggal
java.util.Date tanggalpinjam = df.parse(tgl_kembali.getText());
java.util.Date tanggalkembali = df.parse(tf_tglHariIni.getText());

//Tgl di konversi ke milidetik
long Hari1 = tanggalpinjam.getTime();
long Hari2 = tanggalkembali.getTime();
long diff = Hari2 - Hari1;
long Lama = diff / (24 * 60 * 60 * 1000);

tf_telat.setText(Long.toString(Lama));

    keterlambatan=Integer.parseInt(tf_telat.getText());
    //denda=Integer.parseInt(TxtDenda.getText());
    hasil=1000*keterlambatan;       
    if (hasil < 0) {
        hasil = 0;
    }
    tf_denda.setText(String.valueOf(hasil));
} catch (ParseException e){
}
}
public void waktu(){
    Date tgl = new Date();
    tglpinjam.setDate(tgl);
}
public void cetakkmbl(){
    try {
            String report = ("C:\\Program Files (x86)\\Dreams Team\\Libeeo\\src\\reportEdu\\user_kmbl.jrxml");
            HashMap hash = new HashMap();
            hash.put("user_kmbl", nama_user.getText());
            JasperReport jrpt = JasperCompileManager.compileReport(report);
            JasperPrint jprint = JasperFillManager.fillReport(jrpt, hash, conn);
            JasperViewer.viewReport(jprint, false);
        } catch (JRException Ejrpt) {
            System.out.println("report gagal karena "+Ejrpt);
        }
}
public void pindah(){
        kananpane.removeAll();
        kananpane.repaint();
        kananpane.revalidate();
        //
        kananpane.add(RekapPane);
        kananpane.repaint();
        kananpane.revalidate();
}
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPane;
    private javax.swing.JPanel Librarypane;
    private javax.swing.JPanel MainPane;
    private javax.swing.JPanel RekapPane;
    private javax.swing.JButton brn_pulih;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnArticle;
    private javax.swing.JLabel btnLibrary;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_cetak1;
    private javax.swing.JButton btn_pinjam;
    private javax.swing.JButton btn_preview;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel buku_pinjam;
    private javax.swing.JTextField email_user;
    private javax.swing.JLabel gambarLibrary;
    private javax.swing.JLabel gambar_User;
    private javax.swing.JLabel gambarkiri;
    private javax.swing.JLabel gambarprofile;
    private javax.swing.JLabel gambarrekap;
    private javax.swing.JLabel gambarwelcome;
    private javax.swing.JTextField hp_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel kananpane;
    private javax.swing.JTextField kelas_user;
    private javax.swing.JPanel kiripane;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_kelas_kmbl;
    private javax.swing.JTextField lbl_kelaspinjam;
    private javax.swing.JLabel lbl_kelaspinjam1;
    private javax.swing.JLabel lbl_kelaspinjam2;
    private javax.swing.JLabel lbl_kelaspinjam3;
    private javax.swing.JLabel lbl_kelaspinjam4;
    private javax.swing.JLabel lbl_kelaspinjam5;
    private javax.swing.JLabel lbl_kelaspinjam6;
    private javax.swing.JTextField lbl_no;
    private javax.swing.JLabel lbl_nobuku;
    private javax.swing.JLabel nama_pinjam;
    private javax.swing.JTextField nama_user;
    private javax.swing.JTextField pass_user;
    private javax.swing.JLabel path;
    private javax.swing.JPanel profilepane;
    private javax.swing.JTable tabelRekap;
    private javax.swing.JTextField tf_buku;
    private javax.swing.JTextField tf_cari;
    private javax.swing.JLabel tf_denda;
    private javax.swing.JTextField tf_jmlhBuku;
    private javax.swing.JTextField tf_minus_stok;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JLabel tf_pinjam;
    private javax.swing.JLabel tf_telat;
    private javax.swing.JLabel tf_tglHariIni;
    private javax.swing.JLabel tgl_kembali;
    private javax.swing.JLabel tgl_pinjamac;
    private com.toedter.calendar.JDateChooser tglkmbl;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables
}
