/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ReviewBuku extends javax.swing.JFrame {

    private static Connection conn;
    private static Statement stat;
    private static ResultSet rs;
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    
    
    public ReviewBuku(String no) {
        initComponents();
        conn = Koneksi.koneksi();
//      
        lbl_inputNobuku.setForeground(new Color(0,0,0,0));
        lbl_inputNobuku.setText(no);
        reviewbuku();
//
    }
    
    
    
public void reviewbuku(){
    String nobuku = lbl_inputNobuku.getText();
    try {
        String sql ="select gambar from buku where no ='"+nobuku+"'";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
             if (rs.next()) {
                 byte[] imagedata = rs.getBytes("gambar");
                 format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(lbl_preview.getWidth(), lbl_preview.getHeight(), Image.SCALE_SMOOTH));
        }        lbl_preview.setIcon(format);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan buku "+ e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_preview = new javax.swing.JLabel();
        lbl_inputNobuku = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tampilan Buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 300, -1));
        jPanel1.add(lbl_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 300));

        lbl_inputNobuku.setText("nobuku");
        jPanel1.add(lbl_inputNobuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_inputNobuku;
    private javax.swing.JLabel lbl_preview;
    // End of variables declaration//GEN-END:variables
}
