/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class SignUp extends javax.swing.JFrame {

    private static Connection conn;
    private static Statement stat;
    private static ResultSet rs;
    
    public SignUp() {
        initComponents();
        tf_nama.setBackground(new Color(0,0,0,0));
        tf_hp.setBackground(new Color(0,0,0,0));
        tf_pw.setBackground(new Color(0,0,0,0));
        cb_tampil.setBackground(new Color(0,0,0,0));
        tf_email.setBackground(new Color(0,0,0,0));
        //koneksi
        conn = Koneksi.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup_pane = new javax.swing.JPanel();
        tf_nama = new javax.swing.JTextField();
        tf_hp = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_pw = new javax.swing.JPasswordField();
        tf_kelas = new javax.swing.JTextField();
        cb_tampil = new javax.swing.JCheckBox();
        btn_back = new javax.swing.JLabel();
        button_signin = new javax.swing.JPanel();
        btn_signup = new javax.swing.JLabel();
        gambarSignup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignUp");
        getContentPane().setLayout(new java.awt.CardLayout());

        signup_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_nama.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_nama.setForeground(new java.awt.Color(153, 153, 153));
        tf_nama.setBorder(null);
        tf_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_namaKeyTyped(evt);
            }
        });
        signup_pane.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 231, 220, 33));

        tf_hp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_hp.setForeground(new java.awt.Color(153, 153, 153));
        tf_hp.setBorder(null);
        tf_hp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_hpKeyTyped(evt);
            }
        });
        signup_pane.add(tf_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 220, 33));

        tf_email.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_email.setForeground(new java.awt.Color(153, 153, 153));
        tf_email.setBorder(null);
        signup_pane.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 413, 220, 40));

        tf_pw.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_pw.setForeground(new java.awt.Color(153, 153, 153));
        tf_pw.setBorder(null);
        tf_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pwActionPerformed(evt);
            }
        });
        tf_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_pwKeyTyped(evt);
            }
        });
        signup_pane.add(tf_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 220, 40));

        tf_kelas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_kelas.setForeground(new java.awt.Color(153, 153, 153));
        tf_kelas.setBorder(null);
        tf_kelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_kelasKeyTyped(evt);
            }
        });
        signup_pane.add(tf_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 220, 33));

        cb_tampil.setBackground(new java.awt.Color(255, 255, 255));
        cb_tampil.setForeground(new java.awt.Color(102, 204, 255));
        cb_tampil.setBorder(null);
        cb_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tampilActionPerformed(evt);
            }
        });
        signup_pane.add(cb_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 473, -1, 40));

        btn_back.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("<");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        signup_pane.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        button_signin.setBackground(new java.awt.Color(255, 255, 255));
        button_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_signinMouseExited(evt);
            }
        });

        btn_signup.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(1, 193, 198));
        btn_signup.setText("Sign Up");
        btn_signup.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout button_signinLayout = new javax.swing.GroupLayout(button_signin);
        button_signin.setLayout(button_signinLayout);
        button_signinLayout.setHorizontalGroup(
            button_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_signinLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(btn_signup)
                .addGap(131, 131, 131))
        );
        button_signinLayout.setVerticalGroup(
            button_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_signup, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        signup_pane.add(button_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 350, 40));

        gambarSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/daftarl_libeeo.jpg"))); // NOI18N
        signup_pane.add(gambarSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 600));

        getContentPane().add(signup_pane, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signinMouseEntered
        // TODO add your handling code here:
        button_signin.setBackground(new Color(1,193,198));
        btn_signup.setForeground(Color.white);
    }//GEN-LAST:event_button_signinMouseEntered

    private void button_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signinMouseExited
        // TODO add your handling code here:1,193,198
        button_signin.setBackground(Color.white);
        btn_signup.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_button_signinMouseExited

    private void button_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signinMouseClicked
        // TODO add your handling code here:
        String email2 = tf_email.getText();
        String[] check = email2.split("@", 2);
        button_signin.setBackground(Color.white);
        btn_signup.setForeground(Color.lightGray);
        //register
        String nama = tf_nama.getText();
        String email = tf_email.getText();
        String hp = tf_hp.getText();
        String pw = tf_pw.getText();
        String kelas = tf_kelas.getText();
            if (tf_nama.getText().length()==0) {
                JOptionPane.showMessageDialog(this, "kolom nama kosong");
                }else if(tf_email.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom email kosong");            
                }else if (tf_hp.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom hp kosong");            
                }else if (tf_pw.getText().length()==0) {
                    JOptionPane.showMessageDialog(this, "kolom password kosong");            
                }else if(tf_email.getText().length()<=10){
                    JOptionPane.showMessageDialog(this, "Karakter email terlalu pendek");
                }else if(tf_hp.getText().length()<=10){
                    JOptionPane.showMessageDialog(this, "no Hp terlalu pendek");
                }else if(tf_pw.getText().length()<6){
                    JOptionPane.showMessageDialog(this, "password terlalu pendek");   
                }else if (!"gmail.com".equals(String.valueOf(check[1]))) {
            JOptionPane.showMessageDialog(this, "Isi email dengan benar!!");
                }
                
            else{
                try {
                    String cekmail = "select*from registrasi where email='"+tf_email.getText()+"'";
                    stat = conn.createStatement();
                    rs = stat.executeQuery(cekmail);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Email sudah ada!!!");
                    }else{  
                        try {
                        String sql = "insert into registrasi (email,nama,password,noHP,kelas) values (?,?,?,?,?)";
                            PreparedStatement ps = conn.prepareStatement(sql);
                            ps.setString(1, email);
                            ps.setString(2, nama);
                            ps.setString(3, pw);
                            ps.setString(4, hp);
                            ps.setString(5, kelas);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Berhasil Membuat Akun Baru");
                            new Login().setVisible(true);
                            this.dispose();
                            } catch (HeadlessException | SQLException e) {
                                    JOptionPane.showMessageDialog(this, "gagal membuat akun karena "+e.getMessage());
                        }
                    }
                } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_button_signinMouseClicked

    private void tf_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pwActionPerformed

    private void cb_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tampilActionPerformed
        // tampilkan password
        if (cb_tampil.isSelected()) {
            tf_pw.setEchoChar((char)0);
        }else{
            tf_pw.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_tampilActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        new main_awal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void tf_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_namaKeyTyped
        // TODO add your handling code here:
        if(tf_nama.getText().length()>=50) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Karakter melebihi batas");
        }
    }//GEN-LAST:event_tf_namaKeyTyped

    private void tf_hpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hpKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        else if(tf_hp.getText().length()>=14) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "karakter melebihi batas");
        }
    }//GEN-LAST:event_tf_hpKeyTyped

    private void tf_pwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pwKeyTyped
        // TODO add your handling code here:
        if(tf_pw.getText().length()>=25) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "karakter melebihi batas");
        }
    }//GEN-LAST:event_tf_pwKeyTyped

    private void tf_kelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_kelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kelasKeyTyped
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_signup;
    private javax.swing.JPanel button_signin;
    private javax.swing.JCheckBox cb_tampil;
    private javax.swing.JLabel gambarSignup;
    private javax.swing.JPanel signup_pane;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_kelas;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JPasswordField tf_pw;
    // End of variables declaration//GEN-END:variables

    private void removeAll(JPanel main_pane) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
